//===- registers.dl -----------------------------------------*- datalog -*-===//
//
//  Copyright (C) 2026 GrammaTech, Inc.
//
//  This code is licensed under the GNU Affero General Public License
//  as published by the Free Software Foundation, either version 3 of
//  the License, or (at your option) any later version. See the
//  LICENSE.txt file in the project root for license terms or visit
//  https://www.gnu.org/licenses/agpl.txt.
//
//===----------------------------------------------------------------------===//

reg_map_rule("X0","ZERO").
reg_map_rule("X1","RA").
reg_map_rule("X2","SP").
reg_map_rule("X3","GP").
reg_map_rule("X4","TP").
reg_map_rule("X5","T0").
reg_map_rule("X6","T1").
reg_map_rule("X7","T2").
reg_map_rule("X8","S0").
reg_map_rule("FP","S0").
reg_map_rule("X9","S1").
reg_map_rule("X10","A0").
reg_map_rule("X11","A1").
reg_map_rule("X12","A2").
reg_map_rule("X13","A3").
reg_map_rule("X14","A4").
reg_map_rule("X15","A5").
reg_map_rule("X16","A6").
reg_map_rule("X17","A7").
reg_map_rule("X18","S2").
reg_map_rule("X19","S3").
reg_map_rule("X20","S4").
reg_map_rule("X21","S5").
reg_map_rule("X22","S6").
reg_map_rule("X23","S7").
reg_map_rule("X24","S8").
reg_map_rule("X25","S9").
reg_map_rule("X26","S10").
reg_map_rule("X27","S11").
reg_map_rule("X28","T3").
reg_map_rule("X29","T4").
reg_map_rule("X30","T5").
reg_map_rule("X31","T6").

general_purpose_reg("RA").
general_purpose_reg("SP").
general_purpose_reg("GP").
general_purpose_reg("TP").
general_purpose_reg("T0").
general_purpose_reg("T1").
general_purpose_reg("T2").
general_purpose_reg("S0").
general_purpose_reg("S1").
general_purpose_reg("A0").
general_purpose_reg("A1").
general_purpose_reg("A2").
general_purpose_reg("A3").
general_purpose_reg("A4").
general_purpose_reg("A5").
general_purpose_reg("A6").
general_purpose_reg("A7").
general_purpose_reg("S2").
general_purpose_reg("S3").
general_purpose_reg("S4").
general_purpose_reg("S5").
general_purpose_reg("S6").
general_purpose_reg("S7").
general_purpose_reg("S8").
general_purpose_reg("S9").
general_purpose_reg("S10").
general_purpose_reg("S11").
general_purpose_reg("T3").
general_purpose_reg("T4").
general_purpose_reg("T5").
general_purpose_reg("T6").

function_non_maintained_reg("RA").
function_non_maintained_reg("T0").
function_non_maintained_reg("T1").
function_non_maintained_reg("T2").
function_non_maintained_reg("T3").
function_non_maintained_reg("T4").
function_non_maintained_reg("T5").
function_non_maintained_reg("T6").
function_non_maintained_reg("A0").
function_non_maintained_reg("A1").
function_non_maintained_reg("A2").
function_non_maintained_reg("A3").
function_non_maintained_reg("A4").
function_non_maintained_reg("A5").
function_non_maintained_reg("A6").
function_non_maintained_reg("A7").

pc_reg(""):-
    false.

frame_pointer("S0").

stack_pointer("SP").

return_reg("A0").
return_reg("A1").

condition_flags_reg(""):-
    false.

integer_reg_param("A0",1).
integer_reg_param("A1",2).
integer_reg_param("A2",3).
integer_reg_param("A3",4).
integer_reg_param("A4",5).
integer_reg_param("A5",6).
integer_reg_param("A6",7).
integer_reg_param("A7",8).

zero_reg("ZERO").
